/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccessControl"): TruffleContracts.AccessControlContract;
      require(name: "ERC165"): TruffleContracts.ERC165Contract;
      require(name: "ERC721"): TruffleContracts.ERC721Contract;
      require(
        name: "ERC721Enumerable"
      ): TruffleContracts.ERC721EnumerableContract;
      require(name: "ERC721Full"): TruffleContracts.ERC721FullContract;
      require(name: "ERC721Metadata"): TruffleContracts.ERC721MetadataContract;
      require(name: "IERC165"): TruffleContracts.IERC165Contract;
      require(name: "IERC721"): TruffleContracts.IERC721Contract;
      require(
        name: "IERC721Enumerable"
      ): TruffleContracts.IERC721EnumerableContract;
      require(
        name: "IERC721Metadata"
      ): TruffleContracts.IERC721MetadataContract;
      require(
        name: "IERC721Receiver"
      ): TruffleContracts.IERC721ReceiverContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "NameSystem"): TruffleContracts.NameSystemContract;
      require(name: "SimpleToken"): TruffleContracts.SimpleTokenContract;
    }
  }
}
